// Build step for Vercel (and local use): writes public/js/config.js from env vars
// and copies the supabase-js browser bundle into public/js/vendor/.
//
//   SUPABASE_URL=https://xxxx.supabase.co SUPABASE_ANON_KEY=... npm run build
const fs = require("fs");
const path = require("path");

const url = (process.env.SUPABASE_URL || "").trim();
const key = (process.env.SUPABASE_ANON_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || "").trim();

const missing = [];
if (!/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(url)) missing.push("SUPABASE_URL (like https://abcd.supabase.co)");
if (!key) missing.push("SUPABASE_ANON_KEY");
if (missing.length) {
  console.error(`Build stopped. Set these environment variables: ${missing.join(", ")}`);
  process.exit(1);
}

const root = path.join(__dirname, "..");
const jsDir = path.join(root, "public", "js");

// Only the public URL and publishable (anon) key go to the browser. Never put the service_role key here.
fs.writeFileSync(
  path.join(jsDir, "config.js"),
  `// Generated by scripts/build.js. Do not edit or commit.\nwindow.ECELL_CONFIG = ${JSON.stringify({ supabaseUrl: url, supabaseKey: key })};\n`
);

const vendorDir = path.join(jsDir, "vendor");
fs.mkdirSync(vendorDir, { recursive: true });
fs.copyFileSync(require.resolve("@supabase/supabase-js/dist/umd/supabase.js"), path.join(vendorDir, "supabase.js"));

console.log(`Built config for ${url} and copied supabase-js.`);
