// Build step for Vercel (and local use): writes public/js/config.js from env vars
// and copies the supabase-js browser bundle into public/js/vendor/.
//
//   SUPABASE_URL=https://xxxx.supabase.co SUPABASE_ANON_KEY=... npm run build
const fs = require("fs");
const path = require("path");

// Automatically load local .env if present and variables aren't already set in environment
const envPath = path.join(__dirname, "..", ".env");
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, "utf8");
  for (const line of envContent.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const match = trimmed.match(/^([^=]+)=(.*)$/);
    if (match) {
      const k = match[1].trim();
      const v = match[2].trim().replace(/^["']|["']$/g, "");
      if (!process.env[k]) {
        process.env[k] = v;
      }
    }
  }
}

// Default public credentials for deployment fallbacks (safe publishable keys)
const DEFAULT_URL = "https://kovebqhqibixpdlwgqlr.supabase.co";
const DEFAULT_KEY = "sb_publishable_WWM_JYb8fra9QPoLiUSBjg_xpI75EM-";

let url = (process.env.SUPABASE_URL || DEFAULT_URL).trim().replace(/^["']|["']$/g, "").replace(/\/+$/, "");
const key = (process.env.SUPABASE_ANON_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || DEFAULT_KEY).trim().replace(/^["']|["']$/g, "");

const missing = [];
if (!url) {
  missing.push("SUPABASE_URL (not set)");
} else if (!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(url) && !/^https:\/\/[a-z0-9.-]+/i.test(url)) {
  missing.push(`SUPABASE_URL must be a valid https URL like https://abcd.supabase.co (received "${url}")`);
}
if (!key) {
  missing.push("SUPABASE_ANON_KEY (not set)");
} else if (key.startsWith("sb_secret_")) {
  missing.push("SUPABASE_ANON_KEY is a secret key (sb_secret_...). Use the public anon/publishable key instead.");
} else if (key.split(".").length === 3) {
  try {
    const payload = JSON.parse(Buffer.from(key.split(".")[1], "base64").toString("utf8"));
    if (payload.role === "service_role") {
      missing.push("SUPABASE_ANON_KEY is a service_role key. Never expose service_role in the browser! Use the 'anon' public key.");
    }
  } catch (_) {}
}
if (missing.length) {
  console.error(`Build stopped. Set these environment variables: ${missing.join(", ")}`);
  process.exit(1);
}

const root = path.join(__dirname, "..");
const jsDir = path.join(root, "public", "js");

// Only the public URL and publishable (anon) key go to the browser. Never put the service_role key here.
fs.writeFileSync(
  path.join(jsDir, "config.js"),
  `// Generated by scripts/build.js. Do not edit or commit.\nwindow.ECELL_CONFIG = ${JSON.stringify({ supabaseUrl: url, supabaseKey: key })};\n`
);

const vendorDir = path.join(jsDir, "vendor");
fs.mkdirSync(vendorDir, { recursive: true });
fs.copyFileSync(require.resolve("@supabase/supabase-js/dist/umd/supabase.js"), path.join(vendorDir, "supabase.js"));

console.log(`Built config for ${url} and copied supabase-js.`);
